# Generated by Django 3.1.4 on 2021-05-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='organistaion',
            new_name='organisation',
        ),
    ]
