# Generated by Django 3.1.4 on 2021-06-01 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20210531_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='phoneNumber',
            field=models.CharField(default=9897676879, max_length=20),
            preserve_default=False,
        ),
    ]
